# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PiUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from functools import partial

from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtWidgets import QMainWindow
import DiceReader as DR
from Config import *


class Ui_Logic(QMainWindow):
    CamRadioButtons = []
    Players = 1
    def __init__(self):
        super(Ui_Logic, self).__init__()
        uic.loadUi('PiUi.ui', self)
        self.show()
        self.SaveButton.clicked.connect(SaveConfig)
        self.SettingsButton.clicked.connect(self.RunConfig)
        self.NewGameButton.clicked.connect(self.PlayerSelection)
        self.ContinueButton.clicked.connect(self.ContiuneGameClick)
        self.PlusPlayerButton.clicked.connect(self.PlusPlayer)
        self.MinusPlayerButton.clicked.connect(self.MinusPlayer)
        self.StartButton.clicked.connect(self.NewGameClick)
        self.StartbuttonConfirm.clicked.connect(self.StartButtonConfirmClick)
        self.DiceTakenButton.clicked.connect(self.DiceTaken)
        self.MovePawnBtn.clicked.connect(self.MovePawnOption)
        self.SpawnPawnBtn.clicked.connect(self.SpawnPawnOption)
        self.Pawn1Button.clicked.connect(partial(self.MovePawn, 1))
        self.Pawn2Button.clicked.connect(partial(self.MovePawn, 2))
        self.Pawn3Button.clicked.connect(partial(self.MovePawn, 3))
        self.Pawn4Button.clicked.connect(partial(self.MovePawn, 4))
        self.PawnButtons = [self.Pawn1Button,self.Pawn2Button,self.Pawn3Button,self.Pawn4Button]

    def PlusPlayer(self):
        if(self.Players!=4):
            self.Players = self.Players+1
        self.PlayerNumberSelectLCD.display(self.Players)
    def MinusPlayer(self):
        if (self.Players != 1):
            self.Players = self.Players - 1
        self.PlayerNumberSelectLCD.display(self.Players)


    def GenerateCameras(self):
        i = DR.returnCameraIndexes()
        print(i)
        for j in i:
            self.AddCamera(str(j))
        self.AddCamera("Remote_Camera")

    def AddCamera(self,name):
        self.newRadioButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.newRadioButton.setObjectName(name)
        _translate = QtCore.QCoreApplication.translate
        self.verticalLayout_4.addWidget(self.newRadioButton)
        self.newRadioButton.setText(_translate("MainWindow", name))
        self.CamRadioButtons.append(self.newRadioButton)

    def LoadConfig(self,config):
        for i in Ui_Logic.CamRadioButtons:
            if i.text() == config.Camera:
                i.setChecked(True)
        self.RemoteCameraAddress.setPlainText(config.RemoteCamera)

    def GetCameraAddress(self):
        return self.RemoteCameraAddress.toPlainText()

    def RunConfig(self):
        self.ChangeIndex(5)
    def ChangeIndex(self,index):
        self.stackedWidget.setCurrentIndex(int(index))

    def PlayerSelection(self):
        self.ChangeIndex(4)

    def NewGameClick(self):
        self.server.SendJson("{'Type':'New','Players':'"+str(self.Players)+"'}")
        self.ChangeIndex(7)

    def ContiuneGameClick(self):
        self.server.SendJson("{'Type':'Continue'}")
        self.ChangeIndex(7)

    def getServer(self,s):
        self.server = s

    def SpawnOrMove(self):
        self.ChangeIndex(2)

    def StartButtonConfirmClick(self):
        print("TEST")
        self.server.SendJson("{'Type':'start'}")

    def TakeDiceConfirm(self):
        self.ChangeIndex(8)

    def DiceTaken(self):
        self.server.SendJson("{'Type':'DiceTaken'}")

    def GenerateMoveButtons(self,data):
        try:
            for button in self.PawnButtons:
                button.setEnabled(False)
            #print("And hgerer")
            self.ChangeIndex(6)
            spliteddata = data.replace(" ","").replace("MoveQuestion","").split(";")
            spliteddata = list(filter(lambda x: x != "" ,spliteddata))
            for pawn in spliteddata:
                print(pawn)
                if pawn=='1':
                    self.PawnButtons[0].setEnabled(True)
                if pawn=='2':
                    self.PawnButtons[1].setEnabled(True)
                if pawn=='3':
                    self.PawnButtons[2].setEnabled(True)
                if pawn=='4':
                    self.PawnButtons[3].setEnabled(True)
        except Exception as e:
            print(e)


    def MovePawn(self,pawn):
        print("{'MovePawn':'"+str(pawn)+"'}")
        self.server.SendJson("{'MovePawn':'"+str(pawn)+"'}")

    def SpawnPawnOption(self):
        self.server.SendJson("{'Option':'spawn'}")

    def MovePawnOption(self):
        self.server.SendJson("{'Option':'move'}")

    def SetMovingPawn(self):
        self.ChangeIndex(9)

    def SetRollDice(self):
        self.ChangeIndex(10)
