from PyQt5.QtCore import pyqtSlot
from PyQt5.QtWidgets import QLabel

import DiceReader as dr
import threading
from Server import Server
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        MainWindow.setMinimumSize(QtCore.QSize(480, 320))
        MainWindow.setMaximumSize(QtCore.QSize(480, 320))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.StatusLabel.setGeometry(QtCore.QRect(10, 300, 462, 13))
        self.StatusLabel.setObjectName("StatusLabel")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 451, 291))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.graphicsView = QtWidgets.QGraphicsView(self.page)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 451, 251))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(190, 260, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label = QtWidgets.QLabel(self.page_3)
        self.label.setGeometry(QtCore.QRect(140, 110, 171, 31))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NewGameButton = QtWidgets.QPushButton(self.page_4)
        self.NewGameButton.setObjectName("NewGameButton")
        self.verticalLayout.addWidget(self.NewGameButton)
        self.ContinueButton = QtWidgets.QPushButton(self.page_4)
        self.ContinueButton.setObjectName("ContinueButton")
        self.verticalLayout.addWidget(self.ContinueButton)
        self.SettingsButton = QtWidgets.QPushButton(self.page_4)
        self.SettingsButton.setObjectName("SettingsButton")
        self.verticalLayout.addWidget(self.SettingsButton)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout.setObjectName("gridLayout")
        self.MinusPlayerButton = QtWidgets.QPushButton(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.MinusPlayerButton.setFont(font)
        self.MinusPlayerButton.setObjectName("MinusPlayerButton")
        self.gridLayout.addWidget(self.MinusPlayerButton, 0, 0, 1, 1)
        self.PlayerNumberSelectLCD = QtWidgets.QLCDNumber(self.page_5)
        self.PlayerNumberSelectLCD.setProperty("intValue", 1)
        self.PlayerNumberSelectLCD.setObjectName("PlayerNumberSelectLCD")
        self.gridLayout.addWidget(self.PlayerNumberSelectLCD, 0, 1, 1, 1)
        self.PlusPlayerButton = QtWidgets.QPushButton(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PlusPlayerButton.setFont(font)
        self.PlusPlayerButton.setObjectName("PlusPlayerButton")
        self.gridLayout.addWidget(self.PlusPlayerButton, 0, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalSlider = QtWidgets.QSlider(self.page_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(70, 80, 381, 22))
        self.horizontalSlider.setProperty("value", 99)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.page_2)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(69, 140, 381, 22))
        self.horizontalSlider_2.setProperty("value", 99)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.checkBox = QtWidgets.QCheckBox(self.page_2)
        self.checkBox.setGeometry(QtCore.QRect(370, 180, 81, 17))
        self.checkBox.setObjectName("checkBox")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.StatusLabel.setText(_translate("MainWindow", "Status: "))
        self.pushButton.setText(_translate("MainWindow", "Confirm"))
        self.label.setText(_translate("MainWindow", "Wyszukiwanie klienta gry..."))
        self.NewGameButton.setText(_translate("MainWindow", "New Game"))
        self.ContinueButton.setText(_translate("MainWindow", "Continue"))
        self.SettingsButton.setText(_translate("MainWindow", "Settings"))
        self.MinusPlayerButton.setText(_translate("MainWindow", "-"))
        self.PlusPlayerButton.setText(_translate("MainWindow", "+"))
        self.pushButton_2.setText(_translate("MainWindow", "Start Game"))
        self.checkBox.setText(_translate("MainWindow", "Confirm rolls"))
        self.label_2.setText(_translate("MainWindow", "Effects"))
        self.label_3.setText(_translate("MainWindow", "Music"))


    def ReadDice(self):

        v = dr.readDice()
        self.lcdNumber.display(v)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    s = Server()
    threading.Thread(target = s.Start).start()
    threading.Thread(target = s.Broadcast).start()
    ui.stackedWidget.setCurrentIndex(2)
    sys.exit(app.exec_())

